# Generated by Django 5.2.14 on 2026-07-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_theme_remove_media_profile_remove_page_profile_and_more'),
        ('portfolios', '0008_repair_missing_initial_tables'),
    ]

    operations = [
    ]
